name: My First WorkFlows
on: pull_request
jobs:
  say-pr-received:  
    runs-on:  ubuntu-latest

    steps:
      - name: Print message
        run: echo "Request received, thank you for your contribution!"

